Spring:
  datasource:
    url: jdbc:mysql://testdb1.crxleaq3kvcv.us-east-2.rds.amazonaws.com:3306/testdb
    username: admin
    password: Shyam123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
