Spring:
  datasource:
    url: jdbc:mysql://sql5.freemysqlhosting.net:3306/sql5530434
    username: sql5530434
    password: lpVkdrAVlR

  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: update
